import org.junit.Test;
import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'kellisepp' at '9/27/17 10:44 PM' with Gradle 3.0
 *
 * @author kellisepp, @date 9/27/17 10:44 PM
 */
public class WeatherTest {
    @Test public void testGetCurrentTemperature() {
        Weather weather = new Weather();
        assertTrue("someLibraryMethod should return 'true'", weather.someLibraryMethod());
    }
    
}
