/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'kellisepp' at '9/27/17 10:44 PM' with Gradle 3.0
 *
 * @author kellisepp, @date 9/27/17 10:44 PM
 */
public class Weather {
    public boolean someLibraryMethod() {
        return true;
    }
}
